<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>TypeScriptReact</string>
    <key>scopeName</key>
    <string>source.tsx</string>
    <key>fileTypes</key>
    <array>
      <string>tsx</string>
    </array>
    <key>uuid</key>
    <string>805375ec-d614-41f5-8993-5843fe63ea82</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.shebang.ts</string>
        <key>match</key>
        <string>\A(#!).*(?=$)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.ts</string>
          </dict>
        </dict>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-property</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-binding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-style</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-class</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#svml-code</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.untitled.ts.svml</string>
            <key>match</key>
            <string>(?&lt;!\.|\$)\bsvml\b(?!\$)</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#qstring-single</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#qstring-double</string>
          </dict>
        </array>
      </dict>
      <key>qstring-double</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.ts</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>qstring-single</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.ts</string>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.ts</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\')|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.ts</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.ts</string>
        <key>match</key>
        <string>\\(x\h{2}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
      </dict>
      <key>svml-declaration</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.ts</string>
        <key>match</key>
        <string>(^[A-Z][\w]*)</string>
      </dict>
      <key>svml-property</key>
      <dict>
        <key>name</key>
        <string>variable.ts</string>
        <key>match</key>
        <string>^[\t ]*[#]([\w]*)</string>
      </dict>
      <key>svml-function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.block.ts</string>
            <key>begin</key>
            <string>^[\t ]*([\w]*)\(.*\)\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.untitled.ts</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ts</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>svml-tag</key>
      <dict>
        <key>name</key>
        <string>entity.name.tag.ts</string>
        <key>match</key>
        <string>^[\t ]+[#\w]*:(\w*)</string>
      </dict>
      <key>svml-binding</key>
      <dict>
        <key>name</key>
        <string>entity.name.tag.ts</string>
        <key>match</key>
        <string>^[\t ]+[#:\w]* (\$[\w\.]*)</string>
      </dict>
      <key>svml-class</key>
      <dict>
        <key>name</key>
        <string>variable.other.readwrite.ts.svml</string>
        <key>match</key>
        <string>\[(.*)\]</string>
      </dict>
      <key>svml-style</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.block.ts</string>
            <key>begin</key>
            <string>^[\t ]*(\.[\w]*)\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.untitled.ts</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ts</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.documentation.ts</string>
            <key>begin</key>
            <string>/\*\*(?!/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ts</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#docblock</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.ts</string>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.ts</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.ts</string>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
        </array>
      </dict>
      <key>cast</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx</string>
          </dict>
        </array>
      </dict>
      <key>jsx-tag-attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-tag-attribute-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-tag-attribute-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-string-double-quoted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-string-single-quoted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-evaluated-code</string>
          </dict>
        </array>
      </dict>
      <key>jsx-tag-attribute-name</key>
      <dict>
        <key>match</key>
        <string>(?x)
  \s*
  ([_$a-zA-Z][-$\w]*)
  (?=\s|=|/?&gt;|/\*|//)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.tsx</string>
          </dict>
        </dict>
      </dict>
      <key>jsx-tag-attribute-assignment</key>
      <dict>
        <key>name</key>
        <string>keyword.operator.assignment.tsx</string>
        <key>match</key>
        <string>=(?=\s*(?:'|"|{|/\*|//|\n))</string>
      </dict>
      <key>jsx-string-double-quoted</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.tsx</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.tsx</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.tsx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-entities</string>
          </dict>
        </array>
      </dict>
      <key>jsx-string-single-quoted</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.tsx</string>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.tsx</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.tsx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-entities</string>
          </dict>
        </array>
      </dict>
      <key>jsx-entities</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.entity.tsx</string>
            <key>match</key>
            <string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.entity.tsx</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.entity.tsx</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.bad-ampersand.tsx</string>
            <key>match</key>
            <string>&amp;</string>
          </dict>
        </array>
      </dict>
      <key>jsx-evaluated-code</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.expression.tsx</string>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.tsx</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.tsx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>jsx-tag-attributes-illegal</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.attribute.tsx</string>
        <key>match</key>
        <string>\S+</string>
      </dict>
      <key>jsx-tag-without-attributes</key>
      <dict>
        <key>name</key>
        <string>meta.tag.without-attributes.tsx</string>
        <key>begin</key>
        <string>(&lt;)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;)</string>
        <key>end</key>
        <string>(&lt;/)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.tsx</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.tsx</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.tsx</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.tsx</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>meta.jsx.children.tsx</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-children</string>
          </dict>
        </array>
      </dict>
      <key>jsx-tag-in-expression</key>
      <dict>
        <key>begin</key>
        <string>(?x)
  (?&lt;=[({\[,?=&gt;:*]|&amp;&amp;|\|\||\?|\Wreturn|^return|\Wdefault|^)\s*
  (?!(&lt;)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;)) #look ahead is not start of tag without attributes
  (?!&lt;\s*[_$[:alpha:]][_$[:alnum:]]*((\s+extends\s+[^=&gt;])|,)) # look ahead is not type parameter of arrow
  (?=(&lt;)\s*
  ([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))
  (?=\s+(?!\?)|/?&gt;))</string>
        <key>end</key>
        <string>(/&gt;)|(?:(&lt;/)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.tsx</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.tsx</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.tsx</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-tag</string>
          </dict>
        </array>
      </dict>
      <key>jsx-child-tag</key>
      <dict>
        <key>begin</key>
        <string>(?x)
  (?=(&lt;)\s*
  ([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))
  (?=\s+(?!\?)|/?&gt;))</string>
        <key>end</key>
        <string>(/&gt;)|(?:(&lt;/)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.tsx</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.tsx</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.tsx</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tsx</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-tag</string>
          </dict>
        </array>
      </dict>
      <key>jsx-tag</key>
      <dict>
        <key>name</key>
        <string>meta.tag.tsx</string>
        <key>begin</key>
        <string>(?x)
  (?=(&lt;)\s*
  ([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))
  (?=\s+(?!\?)|/?&gt;))</string>
        <key>end</key>
        <string>(?=(/&gt;)|(?:(&lt;/)\s*([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))\s*(&gt;)))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
  (&lt;)\s*
  ([_$a-zA-Z][-$\w.]*(?&lt;!\.|-))
  (?=\s+(?!\?)|/?&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.tsx</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.tsx</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=[/]?&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#jsx-tag-attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#jsx-tag-attributes-illegal</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.tsx</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=&lt;/)</string>
            <key>contentName</key>
            <string>meta.jsx.children.tsx</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#jsx-children</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>jsx-tag-invalid</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.tag.incomplete.tsx</string>
        <key>match</key>
        <string>&lt;\s*&gt;</string>
      </dict>
      <key>jsx-children</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-tag-without-attributes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-child-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-tag-invalid</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-evaluated-code</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-entities</string>
          </dict>
        </array>
      </dict>
      <key>jsx</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#jsx-tag-without-attributes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-tag-in-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#jsx-tag-invalid</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>